project_id = "bxojxrcerefklsrqkmrs"

[functions.create-checkout]
verify_jwt = false

[functions.sync-lead-to-crm]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.proxy-sec-pdf]
verify_jwt = false